// GET USER
export const GET_PROGRESS="GET_PROGRESS"
export const GET_SUCCESS="GET_SUCCESS"
export const GET_ERROR="GET_ERROR"  

// POST USER
export const POST_PROGRESS="POST_PROGRESS"
export const POST_SUCCESS="POST_SUCCESS"
export const POST_ERROR="POST_ERROR"  

// DELETE USER
export const DELETE_PROGRESS="DELETE_PROGRESS"
export const DELETE_SUCCESS="DELETE_SUCCESS"
export const DELETE_ERROR="DELETE_ERROR"  